version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php:
    build: php
    ports:
      - 9000:9000
    depends_on:
      - mysql
      - redis
      - memcached
      - elasticsearch
      - rabbitmq
    volumes:
      - ${APP_PATH}:/var/www/slimspa/app
      - ${API_PATH}:/var/www/slimspa/api
      - ./logs/slimspa:/var/www/slimspa/api/logs
    environment:
      DEV_STAGE: ${DEV_STAGE}
  nginx:
    build: nginx
    ports:
      - 1934:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - 9200:9200
      - 9300:9300
  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
      - 15672:15672
      - 5672:5672
